---
title: "Schedule"
format: 
  html:
    code-copy: false
---
<html>
<head>
    <style>
        body {
            -webkit-user-select: none; /* Safari */
            -moz-user-select: none; /* Firefox */
            -ms-user-select: none; /* IE10+/Edge */
            user-select: none; /* Standard */
        }
    </style>
</head>
<body>

:::{.callout-note}
**Referencing this presentation:**

Bulusu, Kartik V. (2026, January). MAE 3128 Biomechanics-I. [Course lecture notes, codes and presentations]. Department of Mechanical and Aerospace Engineering, The George Washington University.[https://gwu-mae3128.github.io/spring2026/](https://gwu-mae3128.github.io/spring2026/)

:::

Schedule [*week-by-week*]

::: {.callout-warning appearance="simple"}
**The course schedule below will be updated on a weekly basis during the Spring 2026 semester.**
:::

<!-- ::: {.callout-important appearance="default" title="Final Project Due Date"}
The Final Project deliverables are due on **December 05, 2023, 11:59 PM**. Check-out the schedule to learn more about where to [submit all the deliverables](schedule.qmd#final-project).
::: -->

<style>
        .thumbnail {
            width: 100px; 
            cursor: pointer;
        }

        #popupContainer {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.7);
            justify-content: center;
            align-items: center;
        }

        #popupImage {
            max-width: 80%;
            max-height: 80%;
        }
    </style>

<table class="table table-hover w-auto">
  <colgroup>
    <col style="width:2%">
    <col style="width:28%">
    <col style="width:40%">
    <col style="width:8%">
    <col style="width:22%">
  </colgroup>
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Readings</th>
      <th scope="col">Lecture Topic(s)</th>
      <th scope="col">Practice problems</th>
      <th scope="col">Assignment(s) due</th>
      <!--- <th scope="col">Column heading</th> -->
    </tr>
  </thead>
  <tbody>

<!-- =============== -->   
<!-- WEEK 0 -->
<!-- =============== --> 

  <tr class="table-secondary">
      <th scope="row">Week 0 [01/14/2026]</th>
      <td>
        <ul>
          <li>Ch. 1</li> 
          <li>Ch. 2 (p 47-68)</li> 
        </ul>   
      </td>  
      <td>  
        <ul>          
          <li>Introduction to Biomechanics</li>
          <li>Review of Statics</li>
          <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li>
        </ul>  
      </td>
      <td>
        <ul>
          C1
        </ul>
      </td>
      <td>
        <ul>
          <li>Notes 0</li>
          <li>Notes 1 (01/23)</li>
        </ul>      
      </td>
    </tr>

<tr class="table-secondary">
      <th scope="row">[01/19/2026]</th>
      <td colspan="5" style="text-align: center"> Martin Luther King Jr. Day 
      <br><strong>No Classes</strong>
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
    </tr>

<!-- =============== --> 
<!-- WEEK 1 -->
<!-- =============== --> 

  <tr class="table-secondary">
      <th scope="row">Week 1 [01/21/2026]</th>
      <td>
        <ul>
          <li>Ch. 2 (p 68-100)</li> 
        </ul>   
      </td>  
      <td>  
        <ul>   
          <li>Statics problems in Biomechnanics</li>
          <li>Building blocks of the musculoskeletal system</li>
          <li>Mechanics of the elbow</li>
          <li>Concept of Simple Stress and Simple Strain</li>       
          <!-- <li>Introduction to Stress, Strain, and Constitutive Relationships</li> -->
          <li><a href="Week1.qmd" style="color:red;" target="_blank">Week-1 Notes</a></li>
        </ul>  
      </td>
      <td>
        <ul>
          C2
        </ul>
      </td>
      <td>
        <ul>
          <li>Notes 2 (01/28)</li>
        </ul>      
      </td>
      <!-- <td> Column content</td>  -->
    </tr>

<!-- =============== -->
<!-- WEEK 2 -->
<!-- =============== -->

  <tr class="table-secondary">
      <th scope="row">Week 2 [01/28/2026]</th>
      <td>
        <ul>
          <li>Ch. 3 (p 109-125)</li> 
        </ul>   
      </td>  
      <td>  
        <ul>          
          <li>Stress, Strain, and Constitutive Relationships</li>
          <!-- <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li> -->
        </ul>  
      </td>
      <td>
        <ul>
          C3
        </ul>
      </td>
      <td>
        <ul>
          <li>Notes 3 (02/04)</li>
          <li>Homework 1 (02/04)</li>          
        </ul>      
      </td>
      <!--- <td>Column content</td> -->
    </tr>

<!-- =============== -->
<!-- WEEK 3 -->
<!-- =============== -->

  <tr class="table-secondary">
      <th scope="row">Week 3 [02/04/2026]</th>
      <td>
        <ul>
          <li>Ch. 3 (p 125-155)</li> 
        </ul>   
      </td>  
      <td>  
        <ul>          
          <li>Equilibrium, Universal Solutions, and Inflation</li>
          <!-- <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li> -->
        </ul>  
      </td>
      <td>
        <ul>
          C4
        </ul>
      </td>
      <td>
        <ul>
          <li>Notes 4 (02/11)</li>       
        </ul>      
      </td>
      <!--- <td>Column content</td> -->
    </tr>

<!-- =============== -->  
<!-- WEEK 4 -->
<!-- =============== -->

<tr class="table-secondary">
    <th scope="row">Week 4 [02/11/2026]</th>
    <td>
        <ul>
        </ul>   
      </td>  
      <td>  
        <ul>          
          <li>Equilibrium, Universal Solutions, and Inflation</li>
          <!-- <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li> -->
        </ul>  
      </td>
      <td>
        <ul>
          C5
        </ul>
      </td>
      <td>
        <ul>
          <li>None</li>       
        </ul>      
      </td>
      <!--- <td>Column content</td> -->
    </tr>

<tr class="table-secondary">
      <th scope="row">[02/16/2026]</th>
      <td colspan="5" style="text-align: center"> Presidents' Day 
        <br><strong>No Classes</strong>
      </td> 
    </tr>

<!-- =============== --> 
<!-- WEEK 5 -->
<!-- =============== --> 

<tr class="table-secondary">
      <th scope="row">Week 5 [02/18/2026]</th>
      <td>
        <ul>
        </ul>   
      </td>  
      <td>  
        <ul>          
          <li>Equilibrium, Universal Solutions, and Inflation</li>
          <!-- <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li> -->
        </ul>  
      </td>
      <td>
        <ul>
          C5
        </ul>
      </td>
      <td>
        <ul>
          <li>Homework 2 (02/25)</li>       
        </ul>      
      </td>
      <!--- <td>Column content</td> -->
    </tr>

<!-- =============== -->
<!-- WEEK 6 -->
<!-- =============== -->

<tr class="table-secondary">
      <th scope="row">Week 6 [02/25/2026]</th>
      <td>
        <ul>
          <li>Ch. 4 (p 163-191)</li>
        </ul>   
      </td>  
      <td>  
        <ul>          
          <li>Examination-1 (Chs. 1-3)</li>
          <!-- <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li> -->
        </ul>  
      </td>
      <td>
        <ul>
          C5
        </ul>
      </td>
      <td>
        <ul>
          <li>Notes 5 (03/04)</li>       
        </ul>      
      </td>
      <!--- <td>Column content</td> -->
    </tr>

<!-- =============== -->
<!-- WEEK 7 -->
<!-- =============== -->

<tr class="table-secondary">
    <th scope="row"> Week 7 [03/04/2026]</th>
     <td>
        <ul>
          <li>Ch. 4 (p 163-191)</li>
        </ul>   
      </td>  
      <td>  
        <ul>          
          <li>Extension and Torsion</li>
          <!-- <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li> -->
        </ul>  
      </td>
      <td>
        <ul>
          C6
        </ul>
      </td>
      <td>
        <ul>
          <li>None</li>       
        </ul>      
      </td>
      <!--- <td>Column content</td> -->
    </tr>

<tr class="table-secondary">
      <th scope="row"> [03/09/2025] to [03/11/2026]</th>
      <td colspan="3" style="text-align: center">Spring Break. 
        <br><strong>No class this week</strong>
      </td> 
      <td>
        <ul>
          <li>None</li>       
        </ul>      
      </td>
      <!--- <td>Column content</td> -->
</tr>


<!-- =============== -->
<!-- WEEK 8 -->
<!-- =============== -->

<tr class="table-secondary">
      <th scope="row">Week 8 [03/18/2026]</th>
      <td>
        <ul>
          <li>Ch. 5 (p 213-250)</li>
        </ul>   
      </td>  
      <td>  
        <ul>          
          <li>Extension and Torsion</li>
          <!-- <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li> -->
        </ul>  
      </td>
      <td>
        <ul>
          C7
        </ul>
      </td>
      <td>
        <ul>
          <li>Notes 6 (3/18)</li>       
        </ul>      
      </td>
      <!--- <td>Column content</td> -->
    </tr>

<!-- =============== -->
<!-- WEEK 9 -->
<!-- =============== -->

<tr class="table-secondary">
    <th scope="row">Week 9 [03/25/2026]</th>
    <td>
        <ul>
        </ul>   
      </td>  
      <td>  
        <ul>          
          <li>No Scheduled Class, but this is subject to change</li>
          <!-- <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li> -->
        </ul>  
      </td>
      <td>
        <ul>
        </ul>
      </td>
      <td>
        <ul>
          <li>None</li>       
        </ul>      
      </td>
      <!--- <td>Column content</td> -->
    </tr>

<!-- =============== -->
<!-- WEEK 10 -->
<!-- =============== -->

<tr class="table-secondary">
      <th scope="row">Week 10 [04/01/2026]</th>
      <td>
        <ul>
          <li>Ch. 5 (p 250-278)</li>
        </ul>   
      </td>  
      <td>  
        <ul>          
          <li>Bending and Buckling</li>
          <!-- <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li> -->
        </ul>  
      </td>
      <td>
        <ul>
          C8
        </ul>
      </td>
      <td>
        <ul>
          <li>Notes 7 (04/01)</li>   
          <li>Homework 3 (04/08)</li>               
        </ul>      
      </td>
      <!--- <td>Column content</td> -->
    </tr>


<!-- =============== -->
<!-- WEEK 11 -->
<!-- =============== -->

<tr class="table-secondary">
      <th scope="row">Week 11 [04/08/2026]</th>
      <td>
        <ul>
          <li>Ch. 6 (p 289-307)</li>
        </ul>   
      </td>  
      <td>  
        <ul>          
          <li>Bending and Buckling</li>
          <!-- <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li> -->
        </ul>  
      </td>
      <td>
        <ul>
          C9
        </ul>
      </td>
      <td>
        <ul>
          <li>Notes 8 (04/08)</li>            
        </ul>      
      </td>
      <!--- <td>Column content</td> -->
    </tr>


<!-- =============== -->
<!-- WEEK 12 -->
<!-- =============== -->

<tr class="table-secondary">
      <th scope="row">Week 12 [04/15/2026]</th>
      <td>
        <ul>
        </ul>   
      </td>  
      <td>  
        <ul>          
          <li>Nonlinear Problems</li>
          <!-- <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li> -->
        </ul>  
      </td>
      <td>
        <ul>
          C10
        </ul>
      </td>
      <td>
        <ul>
          <li>Notes 9 (04/15)</li>             
        </ul>      
      </td>
      <!--- <td>Column content</td> -->
    </tr>

<!-- =============== -->
<!-- WEEK 13 -->
<!-- =============== -->

<tr class="table-secondary">
      <th scope="row"> Week 13 [04/22/2026]</th>
      <td>
        <ul>
        </ul>   
      </td>  
      <td>  
        <ul>          
          <li>Review</li>
          <li>Examination-2 (Chs. 4-6)</li>
          <!-- <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li> -->
        </ul>  
      </td>
      <td>
        <ul>
        </ul>
      </td>
      <td>
        <ul>
          <li>Homework 4 (4/27)</li>             
        </ul>      
      </td>
      <!--- <td>Column content</td> -->
</tr>    


<tr class="table-secondary">
      <th scope="row">[04/27/2026]</th>
      <td colspan="5" style="text-align: center"> Last Day of Classes
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr> 

<tr class="table-secondary">
      <th scope="row">[04/28/2026]</th>
      <td colspan="5" style="text-align: center"> Make up day
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr>    

<tr class="table-secondary">
      <th scope="row">[04/29/2026]</th>
      <td colspan="5" style="text-align: center"> Desginated Monday
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr>   
<tr class="table-secondary">
      <th scope="row">[04/30/2026] to [05/01/2026]</th>
      <td colspan="5" style="text-align: center"> Reading Days
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr>  
   
<tr class="table-secondary">
      <th scope="row">[05/02/2026] to [05/08/2026]</th>
      <td colspan="5" style="text-align: center"> <strong>Final Examination Week. **There is no Final Exam for this course.** </strong>
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr>        
<tr class="table-secondary">
      <th scope="row">[05/14/2026] to [05/17/2026]</th>
      <td colspan="5" style="text-align: center"> Commencement Weekend
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr>    
  </tbody>
</table>



<!-- <footer>
  <p>This is a Quarto website. To learn more about Quarto websites visit <https://quarto.org/docs/websites>.<br>
  Author: Kartik Bulusu<br>
  Contact: <a href="mailto:bulusu@gwu.edu">bulusu</a><br>
  &copy; 2024 All rights reserved</p>
</footer> -->
